version: '0.3.0.{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda35-x64"

install:
  - call %PYTHON_LOC%\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

build_script:
  - conda env create --file environment.yml
  - call %PYTHON_LOC%\Scripts\activate.bat esdl
  - python setup.py install
  - conda list
  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
  - set NUMBA_DISABLE_JIT=1
  - py.test -v test --ignore=test/providers
